import enum


class UserRole(str, enum.Enum):
    ADMIN = "ADMIN"
    LOCAL_HR = "LOCAL_HR"
    HEAD_OFFICE_HR = "HEAD_OFFICE_HR"
    DEPARTMENT_HEAD = "DEPARTMENT_HEAD"
    SALARY_TEAM = "SALARY_TEAM"


class PipelineStage(str, enum.Enum):
    NEW_APPLICATION = "NEW_APPLICATION"
    AWAITING_LOCAL_INTERVIEW = "AWAITING_LOCAL_INTERVIEW"
    LOCAL_HR_REVIEW_COMPLETE = "LOCAL_HR_REVIEW_COMPLETE"
    AWAITING_HEAD_OFFICE_INTERVIEW = "AWAITING_HEAD_OFFICE_INTERVIEW"
    HEAD_OFFICE_INTERVIEW_COMPLETE = "HEAD_OFFICE_INTERVIEW_COMPLETE"
    SUITABLE_FOR_HIRE = "SUITABLE_FOR_HIRE"
    SALARY_PENDING = "SALARY_PENDING"
    SALARY_APPROVED = "SALARY_APPROVED"
    OFFER_SENT = "OFFER_SENT"
    OFFER_ACCEPTED = "OFFER_ACCEPTED"
    OFFER_DECLINED = "OFFER_DECLINED"
    JOINING_SCHEDULED = "JOINING_SCHEDULED"
    JOINED = "JOINED"
    REJECTED = "REJECTED"
    ON_HOLD = "ON_HOLD"


class SourceChannel(str, enum.Enum):
    WALK_IN = "WALK_IN"
    INDEED = "INDEED"
    REFERRAL = "REFERRAL"
    CAMPUS = "CAMPUS"
    OTHER = "OTHER"


class RemarkStageContext(str, enum.Enum):
    LOCAL_HR = "LOCAL_HR"
    HEAD_OFFICE_HR = "HEAD_OFFICE_HR"
    TECHNICAL_TEST = "TECHNICAL_TEST"
    DEPT_HEAD = "DEPT_HEAD"


class DocumentFileType(str, enum.Enum):
    RESUME = "RESUME"
    ID_PROOF = "ID_PROOF"
    EDUCATION_CERT = "EDUCATION_CERT"
    OFFER_LETTER = "OFFER_LETTER"
    JOINING_FORM = "JOINING_FORM"
    OTHER = "OTHER"


class MessageChannel(str, enum.Enum):
    WHATSAPP = "WHATSAPP"
    EMAIL = "EMAIL"
    SMS = "SMS"


class MessageStatus(str, enum.Enum):
    PENDING = "PENDING"
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"
