"""Department technical-test banks (CR, Accounts, HR, Systems, Projects, Insurance, Marketing, Finance, Training)."""
from __future__ import annotations

from app.core.positions import (
    PAPER_ACCOUNTS,
    PAPER_CR_EXPERIENCED,
    PAPER_CR_FRESHER,
    PAPER_FINANCE,
    PAPER_HR,
    PAPER_INSURANCE,
    PAPER_MARKETING,
    PAPER_PROJECTS,
    PAPER_SYSTEMS,
    PAPER_TRAINING,
)

CR_FRESHER = [
    ("R1", "Which of the following is the primary objective of the Customer Relations Department?",
     {"A": "Increase vehicle production", "B": "Ensure customer satisfaction and build long-term relationships",
      "C": "Reduce service costs", "D": "Increase showroom space"}, "B"),
    ("R2", "If a customer is upset about a service delay, what should you do first?",
     {"A": "Ignore the complaint", "B": "Listen carefully, apologize, and explain the situation politely",
      "C": "Tell the customer to explain the issue", "D": "Ask the customer to contact another department"}, "B"),
    ("R3", "What is the most important quality of a Customer Relation Executive?",
     {"A": "Communication skills", "B": "Driving skills",
      "C": "Mechanical knowledge", "D": "Typing speed"}, "A"),
    ("R4", "Why is customer feedback important?",
     {"A": "To increase employee salary", "B": "To improve customer service and satisfaction",
      "C": "To reduce vehicle prices", "D": "To increase showroom sales"}, "B"),
    ("R5", "Which of the following is an example of good customer service?",
     {"A": "Making the customer wait without explanation", "B": "Speaking politely and providing accurate information",
      "C": "Ignoring customer calls", "D": "Arguing with the customer"}, "B"),
    ("R6", "If you do not know the answer to a customer's question, what should you do?",
     {"A": "Convert to another topic",
      "B": "Politely inform the customer that you will check and provide the correct information",
      "C": "Ignore the question", "D": "End the conversation"}, "B"),
    ("R7", "Which department should a customer complaint be communicated to for quick resolution?",
     {"A": "The concerned department/service advisor", "B": "Security",
      "C": "Housekeeping", "D": "Reception only"}, "A"),
    ("R8", "What should you do after resolving a customer complaint?",
     {"A": "Close the case without informing the customer",
      "B": "Follow up with the customer to ensure satisfaction",
      "C": "Wait for the customer to call again", "D": "Delete the complaint record"}, "B"),
    ("R9", "Which of the following creates the best first impression with a customer?",
     {"A": "Professional appearance, smile, and polite communication", "B": "Speaking loudly",
      "C": "Using mobile phone while talking", "D": "Keeping the customer waiting"}, "A"),
    ("R10", "Why is teamwork important in a Toyota dealership?",
     {"A": "To complete customer requests efficiently and provide better service",
      "B": "To reduce working hours", "C": "To avoid talking to customers", "D": "To reduce vehicle sales"}, "A"),
]

CR_EXPERIENCED = [
    ("R1", "A customer walks into the showroom in an angry state. What should be your first action as a Customer Relation Executive?",
     {"A": "Listen to the complaint and initiate corrective action.",
      "B": "Seek clarification from the concerned department first.",
      "C": "Immediately involve the Service Manager.",
      "D": "Register the complaint in the CRM before speaking to the customer."}, "A"),
    ("R2", "What is the most important aspect of handling a customer complaint?",
     {"A": "Closing the complaint within the target time.",
      "B": "Identifying the root cause and ensuring customer satisfaction.",
      "C": "Avoiding complaint escalation.", "D": "Updating all details in the CRM."}, "B"),
    ("R3", "Which is the most appropriate indicator of a Customer Relation Executive's performance?",
     {"A": "Complaint Closure Rate", "B": "CSAT & Customer Feedback",
      "C": "Daily Call Count", "D": "CRM Case Updates"}, "B"),
    ("R4", "If a customer reports the same issue again, what is the most appropriate action?",
     {"A": "Review the complaint history and identify the root cause.",
      "B": "Register it as a new complaint.",
      "C": "Forward it only to the Service Advisor.", "D": "Check the warranty status first."}, "A"),
    ("R5", "If there is a delay in vehicle delivery, what is the best way to inform the customer?",
     {"A": "Clearly explain the reason and provide a revised timeline.",
      "B": "Inform the customer only when the vehicle is ready.",
      "C": "Ask the customer to contact the Sales Consultant.",
      "D": "Simply apologize and end the conversation."}, "A"),
    ("R6", "Which departments does the Customer Relation Department primarily coordinate with in a Toyota dealership?",
     {"A": "Sales, Service, Accounts & Finance", "B": "U-Trust & Accessories",
      "C": "Insurance & Warranty", "D": "All above"}, "D"),
    ("R7", "What is the name of Toyota's Battery Electric SUV?",
     {"A": "Urban Cruiser", "B": "Urban Cruiser Hyryder",
      "C": "Urban Cruiser Taisor", "D": "Urban Cruiser Ebella"}, "D"),
    ("R8", "A customer is interested in purchasing a Toyota Hybrid vehicle. What is the most appropriate action?",
     {"A": "Explain the basic benefits of Hybrid technology and connect the customer with a Sales Consultant.",
      "B": "Provide only the product brochure.",
      "C": "Explain all the technical specifications yourself.",
      "D": "Directly book a test drive."}, "A"),
    ("R9", "A customer asks about Toyota's latest vehicle models. What is the most professional approach?",
     {"A": "Share official information and connect the customer with the Sales Consultant.",
      "B": "Share information from social media.",
      "C": "Ask the customer to wait until the vehicle arrives.",
      "D": "Ask the customer to visit the website."}, "A"),
    ("R10", "What is the primary reason Toyota has earned a strong global reputation?",
     {"A": "Reliability, Quality & Durability (QDR)", "B": "Low pricing",
      "C": "Attractive offers and discounts", "D": "Wide range of vehicle models"}, "A"),
]

ACCOUNTS = [
    ("R1", "What is the basic accounting equation?",
     {"A": "Assets = Liabilities + Capital", "B": "Assets = Sales + Expenses",
      "C": "Capital = Sales + Purchases", "D": "Liabilities = Assets + Expenses"}, "A"),
    ("R2", "What does GST stand for?",
     {"A": "Goods and Services Tax", "B": "General Sales Transaction",
      "C": "Government Service Tax", "D": "Goods Supply Total"}, "A"),
    ("R3", "What is a GSTIN?",
     {"A": "Goods and Services Tax Identification Number",
      "B": "General Sales Tax Invoice Number",
      "C": "Government Service Identification Number",
      "D": "Goods Stock Identification Number"}, "A"),
    ("R4", "What is accounts payable?",
     {"A": "Money owed by the business to suppliers/creditors",
      "B": "Money customers owe the business", "C": "Cash in hand", "D": "Vehicle sales revenue"}, "A"),
    ("R5", "What is a bank reconciliation statement (BRS)?",
     {"A": "Statement comparing cash sales and credit sales",
      "B": "Statement used to reconcile the bank book with the bank statement",
      "C": "Statement of vehicle stock", "D": "Statement of customer complaints"}, "B"),
    ("R6", "What does NEFT stand for?",
     {"A": "National Electronic Funds Transfer", "B": "National Exchange Fund Transaction",
      "C": "New Electronic Finance Transfer", "D": "National Easy Fund Transfer"}, "A"),
    ("R7", "What does RTGS stand for?",
     {"A": "Real Time Gross Settlement", "B": "Real Transfer General System",
      "C": "Retail Transaction Government Service", "D": "Real Tax Gross System"}, "A"),
    ("R8", "What does UPI stand for?",
     {"A": "Unified Payments Interface", "B": "Universal Payment India",
      "C": "United Payment Instrument", "D": "User Payment Interface"}, "A"),
    ("R9", "What is IFSC?",
     {"A": "Indian Financial System Code", "B": "Indian Fund Settlement Code",
      "C": "International Financial Service Code", "D": "Indian Finance Security Certificate"}, "A"),
    ("R10", "Why should the payment reference/UTR number be recorded?",
     {"A": "To help identify and track the bank transaction",
      "B": "To identify the vehicle engine number",
      "C": "To calculate vehicle mileage", "D": "To prepare a driving licence"}, "A"),
    ("R11", "What is an outstanding cheque?",
     {"A": "A cheque issued but not yet presented/cleared through the bank",
      "B": "A cancelled cheque", "C": "A cheque without a signature", "D": "A cash payment"}, "A"),
    ("R12", "What is a cheque deposit in transit?",
     {"A": "A cheque recorded in the books but not yet credited by the bank",
      "B": "A cheque already returned to the customer",
      "C": "A cheque that has been cancelled", "D": "A cash withdrawal"}, "A"),
    ("R13", "Cash Book balance is ₹1,00,000. A cheque issued for ₹20,000 has not yet been presented. What would the bank statement balance generally be, before considering other differences?",
     {"A": "₹80,000", "B": "₹1,00,000", "C": "₹1,20,000", "D": "₹20,000"}, "C"),
    ("R14", "Which of the following should an Accounts Executive check during BRS?",
     {"A": "Cheques issued", "B": "Cheques deposited",
      "C": "Bank charges and direct credits/debits", "D": "All of the above"}, "D"),
]

HR = [
    ("R1", "What is a job description (JD)?",
     {"A": "A document describing the responsibilities, duties and requirements of a job",
      "B": "The qualifications, skills, experience and other requirements expected from a candidate",
      "C": "A company balance sheet", "D": "Choosing the most suitable candidate for a job"}, "A"),
    ("R2", "What is a job specification?",
     {"A": "The qualifications, skills, experience and other requirements expected from a candidate",
      "B": "A document describing the responsibilities, duties and requirements of a job",
      "C": "Attracting and identifying potential candidates for job vacancies",
      "D": "A salary payment receipt"}, "A"),
    ("R3", "What is employee retention?",
     {"A": "Efforts to keep employees in the organization", "B": "Recruiting only new employees",
      "C": "Terminating employees", "D": "Reducing salaries"}, "A"),
    ("R4", "What does HRMS stand for?",
     {"A": "Human Resources Management System", "B": "Human Recruitment Management Service",
      "C": "Human Record Monitoring System", "D": "Human Revenue Management Software"}, "A"),
    ("R5", "What is employee attrition/turnover?",
     {"A": "Employees leaving an organization over a period", "B": "Employee promotion",
      "C": "Employee training", "D": "Employee attendance"}, "A"),
    ("R6", "Why are KPIs used?",
     {"A": "To measure performance against defined objectives or indicators",
      "B": "To calculate employee age", "C": "To register employees", "D": "To Select a Candidate"}, "A"),
    ("R7", "What does EPFO stand for?",
     {"A": "Employees' Provident Fund Organisation", "B": "Employee Pension Finance Organisation",
      "C": "Employment Provident Fund Office", "D": "Employees' Payment Fund Organisation"}, "A"),
    ("R8", "What does ESIC stand for?",
     {"A": "Employees' State Insurance Corporation", "B": "Employee Salary Insurance Company",
      "C": "Employment Security Insurance Council", "D": "Employees' Service Information Corporation"}, "A"),
    ("R9", "What is gratuity?",
     {"A": "A statutory terminal benefit payable to eligible employees subject to applicable law",
      "B": "Monthly salary", "C": "Travel allowance", "D": "Performance bonus only"}, "A"),
    ("R10", "Which law governs gratuity in India?",
     {"A": "Payment of Gratuity Act, 1972", "B": "Payment of Bonus Act only",
      "C": "Factories Act only", "D": "Companies Act only"}, "A"),
    ("R11", "Which qualities are most important for an HR Person?",
     {"A": "Communication, confidentiality, accuracy, coordination and people skills",
      "B": "Recruiting good Manpower's", "C": "Team Player", "D": "Coordination Skill only"}, "A"),
]

SYSTEMS = [
    ("R1", "What happens to data stored in RAM when the computer is switched off?",
     {"A": "It is normally lost", "B": "It is permanently saved",
      "C": "It is transferred to the printer", "D": "It is uploaded automatically"}, "A"),
    ("R2", "Which device is primarily used for permanent data storage?",
     {"A": "SSD/HDD", "B": "RAM", "C": "CPU cache only", "D": "Keyboard"}, "A"),
    ("R3", "What does IP stand for?",
     {"A": "Internet Protocol", "B": "Internal Program",
      "C": "Internet Process", "D": "Information Provider"}, "A"),
    ("R4", "What does DNS stand for?",
     {"A": "Domain Name System", "B": "Digital Network Service",
      "C": "Data Name Server", "D": "Domain Network Security"}, "A"),
    ("R5", "What does DHCP do?",
     {"A": "Automatically assigns network configuration such as IP addresses",
      "B": "Scans for viruses", "C": "Creates backups", "D": "Encrypts emails"}, "A"),
    ("R6", "What is a software patch?",
     {"A": "An update that may fix bugs, improve functionality or address security vulnerabilities",
      "B": "A network cable", "C": "A type of monitor", "D": "A backup device"}, "A"),
    ("R7", "What is phishing?",
     {"A": "A fraudulent attempt to obtain sensitive information by pretending to be trustworthy",
      "B": "A method of backing up files", "C": "A network configuration protocol", "D": "A Windows update"}, "A"),
    ("R8", "A user has forgotten their password. What should the System Administrator do?",
     {"A": "Follow the organization's authorized password-reset/identity-verification procedure",
      "B": "Tell the user another employee's password",
      "C": "Disable security controls", "D": "Share the administrator password"}, "A"),
    ("R9", "What is MFA?",
     {"A": "Multi-Factor Authentication", "B": "Main File Access",
      "C": "Multiple Firewall Application", "D": "Managed File Administration"}, "A"),
    ("R10", "Which command is used to display the current IP configuration in Windows?",
     {"A": "ping", "B": "ipconfig", "C": "nslookup", "D": "tracert"}, "B"),
    ("R11", "Which protocol is commonly used for secure web browsing?",
     {"A": "HTTP", "B": "HTTPS", "C": "FTP", "D": "SMTP"}, "B"),
    ("R12", "Which command can be used to test DNS name resolution?",
     {"A": "nslookup", "B": "format", "C": "mkdir", "D": "taskkill"}, "A"),
    ("R13", "What should you do if you receive a suspicious email attachment?",
     {"A": "Open it immediately",
      "B": "Verify/report it according to security procedures and avoid opening it",
      "C": "Forward it to everyone", "D": "Disable antivirus"}, "B"),
    ("R14", "What is cloud computing?",
     {"A": "Providing computing resources/services over a network, typically the internet",
      "B": "Storing files only on USB drives", "C": "A type of keyboard", "D": "A printer technology"}, "A"),
]

INSURANCE = [
    ("R1", "Who is an insurer?",
     {"A": "The insurance company that provides insurance cover", "B": "The vehicle owner",
      "C": "The dealer", "D": "The RTO"}, "A"),
    ("R2", "What is IDV?",
     {"A": "Insured Declared Value", "B": "Insurance Document Verification",
      "C": "Insured Dealer Value", "D": "Insurance Deposit Value"}, "A"),
    ("R3", "What does NCB stand for?",
     {"A": "No Claim Bonus", "B": "New Car Benefit",
      "C": "National Claim Bureau", "D": "New Coverage Benefit"}, "A"),
    ("R4", "What is the primary difference between third-party liability and own-damage cover?",
     {"A": "Third-party covers damage to the insured vehicle only",
      "B": "Own-damage covers third-party legal liability only",
      "C": "Third-party covers specified liability to third parties, while own-damage covers specified loss/damage to the insured vehicle",
      "D": "There is no difference"}, "C"),
    ("R5", "What is the main purpose of an insurance deductible/excess?",
     {"A": "It is the portion of an admissible claim that the insured may have to bear as specified by the policy",
      "B": "It is the insurance company's profit",
      "C": "It is the vehicle's resale price", "D": "It is the GST amount"}, "A"),
    ("R6", "A customer changes the vehicle's registration details after purchasing the policy. What should the insurance executive generally do?",
     {"A": "Ignore the change",
      "B": "Ensure the policy records are updated through the insurer's prescribed process",
      "C": "Cancel the policy immediately", "D": "Manually alter the policy document"}, "B"),
    ("R7", "What is an insurance exclusion?",
     {"A": "A situation, loss or circumstance that is not covered under the policy",
      "B": "A bonus given to the customer", "C": "A type of insurance premium",
      "D": "A vehicle registration fee"}, "A"),
    ("R8", "A policy has an exclusion for a particular type of loss. What does this mean?",
     {"A": "That loss may not be covered under the policy, subject to the exact policy wording",
      "B": "The insurer must always pay", "C": "The customer gets double compensation",
      "D": "The premium becomes refundable automatically"}, "A"),
    ("R9", "What is the purpose of policy endorsement?",
     {"A": "To formally record an approved change/amendment to an existing insurance policy",
      "B": "To cancel every claim", "C": "A bonus given to the customer",
      "D": "To replace the vehicle RC"}, "A"),
    ("R10", "Which statement about an insurance policy is MOST accurate?",
     {"A": "Every loss involving the insured vehicle is automatically covered",
      "B": "Coverage depends on the policy's terms, conditions, exclusions, limits and applicable law",
      "C": "The dealer decides all claims", "D": "The customer decides the claim amount"}, "B"),
]

MARKETING = [
    ("R1", "What is SEO?",
     {"A": "Search Engine Optimization", "B": "Sales Executive Operation",
      "C": "Service Efficiency Organization", "D": "Search Employee Office"}, "A"),
    ("R2", "What is social media marketing?",
     {"A": "Promoting products/services through social media platforms",
      "B": "Selling vehicles only through the showroom",
      "C": "Repairing vehicles through social media", "D": "Managing employee attendance"}, "A"),
    ("R3", "Which statement best describes ROAS?",
     {"A": "Revenue attributed to advertising divided by advertising spend",
      "B": "Total profit divided by employee count",
      "C": "Sales divided by showroom area", "D": "Leads divided by customers"}, "A"),
    ("R4", "What is lead nurturing?",
     {"A": "Maintaining relevant communication with prospects until they are ready to take the desired action",
      "B": "Deleting old leads", "C": "Increasing vehicle prices",
      "D": "Repairing test-drive vehicles"}, "A"),
    ("R5", "What is referral marketing?",
     {"A": "Encouraging existing customers or other sources to recommend potential customers",
      "B": "Selling vehicles only through advertisements",
      "C": "Buying competitor vehicles", "D": "Reducing workshop staff"}, "A"),
    ("R6", "What is brand positioning different from product positioning?",
     {"A": "Brand positioning concerns the broader perception of the brand, while product positioning focuses on a particular product/model",
      "B": "They are always exactly the same",
      "C": "Brand positioning applies only to employees",
      "D": "Product positioning applies only to workshops"}, "A"),
    ("R7", "What is SWOT analysis?",
     {"A": "Strengths, Weaknesses, Opportunities and Threats",
      "B": "Sales, Warranty, Operations and Training",
      "C": "Service, Warranty, Offers and Targets",
      "D": "Strategy, Workforce, Operations and Technology"}, "A"),
    ("R8", "A new competitor entering the dealership's market is generally a:",
     {"A": "Strength", "B": "Weakness", "C": "Opportunity", "D": "Threat"}, "D"),
    ("R9", "Which metric measures the percentage of people who click an advertisement after seeing it?",
     {"A": "CTR", "B": "ROI", "C": "CAC", "D": "CLV"}, "A"),
    ("R10", "What does CPC stand for?",
     {"A": "Cost Per Click", "B": "Customer Per Campaign",
      "C": "Cost Per Customer", "D": "Campaign Performance Calculation"}, "A"),
    ("R11", "What is the BEST way to evaluate an automobile marketing campaign?",
     {"A": "Evaluate relevant metrics such as qualified leads, conversion, acquisition cost, revenue and ROI/ROAS along with business objectives",
      "B": "Look only at impressions", "C": "Look only at the number of clicks",
      "D": "Look only at social-media followers"}, "A"),
]

FINANCE = [
    ("R1", "What is the principal amount in a vehicle loan?",
     {"A": "The amount borrowed before applicable interest/charges",
      "B": "Total interest paid", "C": "Monthly EMI", "D": "Insurance premium"}, "A"),
    ("R2", "What is KYC?",
     {"A": "Know Your Customer", "B": "Keep Your Credit",
      "C": "Know Your Company", "D": "Key Yield Calculation"}, "A"),
    ("R3", 'A customer asks the Finance Coordinator, "Can you guarantee that my loan will be approved?" What is the correct response?',
     {"A": "Guarantee approval",
      "B": "Explain that final approval depends on the lender's credit assessment and applicable criteria",
      "C": "Promise approval if the customer pays a fee",
      "D": "Ask the salesperson to guarantee it"}, "B"),
    ("R4", "Why is document fraud a serious issue in retail finance?",
     {"A": "It can create financial, legal and compliance risks",
      "B": "It only delays vehicle delivery", "C": "It improves loan approval",
      "D": "It reduces insurance premium"}, "A"),
    ("R5", "Two lenders offer the same interest rate but different processing fees and tenures. What should the coordinator compare?",
     {"A": "Only the EMI", "B": "Overall loan cost, EMI, tenure, fees and applicable terms",
      "C": "Only the lender's brand name", "D": "Only the processing fee"}, "B"),
    ("R6", "What is the commonly used CIBIL score range for individuals?",
     {"A": "0–500", "B": "300–900", "C": "500–1,000", "D": "100–800"}, "B"),
    ("R7", "Does a high CIBIL score guarantee vehicle-loan approval?",
     {"A": "Yes, always", "B": "No, lenders consider multiple factors",
      "C": "Yes, if the customer has a salary", "D": "Yes, if the vehicle is new"}, "B"),
    ("R8", "What is the difference between a credit report and a credit score?",
     {"A": "A report contains detailed credit information; a score is a numerical indicator derived from credit information",
      "B": "They are exactly the same", "C": "A report is only for vehicles",
      "D": "A score contains all account details"}, "A"),
    ("R9", "Which is the BEST statement for an Automobile Retail Finance Coordinator?",
     {"A": "A good CIBIL score can be helpful, but final approval depends on the lender's complete assessment and applicable policies.",
      "B": "A CIBIL score above 750 guarantees approval.",
      "C": "The dealership can change your CIBIL score.",
      "D": "CIBIL is the only factor considered by banks."}, "A"),
    ("R10", "What is the most important professional principle for an experienced Retail Finance Coordinator?",
     {"A": "Get every loan approved regardless of circumstances",
      "B": "Balance customer service with accuracy, confidentiality, compliance and proper lender procedures",
      "C": "Promise customers guaranteed approval",
      "D": "Modify documents to achieve targets"}, "B"),
]

PROJECTS = [
    ("R1", "What is the full form of RCC?",
     {"A": "Reinforced Cement Concrete", "B": "Reinforced Construction Cement",
      "C": "Ready Cement Concrete", "D": "Reinforced Concrete Construction"}, "A"),
    ("R2", "Which material is mainly used to provide tensile strength in RCC?",
     {"A": "Sand", "B": "Steel reinforcement", "C": "Cement", "D": "Aggregate"}, "B"),
    ("R3", "What does PCC stand for?",
     {"A": "Plain Cement Concrete", "B": "Precast Cement Construction",
      "C": "Portland Concrete Construction", "D": "Plain Construction Cement"}, "A"),
    ("R4", "What is the purpose of water in concrete?",
     {"A": "It helps cement hydration and workability", "B": "It only increases weight",
      "C": "It replaces aggregate", "D": "It prevents cement hydration"}, "A"),
    ("R5", "What generally happens if excessive water is added to concrete?",
     {"A": "Strength can decrease", "B": "Strength always increases",
      "C": "Cement becomes steel", "D": "Aggregate disappears"}, "A"),
    ("R6", "Which test is commonly used to determine the compressive strength of concrete?",
     {"A": "Compression test on concrete specimens", "B": "Slump test only",
      "C": "Sieve analysis", "D": "Vicat test"}, "A"),
    ("R7", "Which type of foundation is commonly used when the soil near the surface has adequate bearing capacity?",
     {"A": "Shallow foundation", "B": "Deep foundation only",
      "C": "Floating foundation only", "D": "Suspension foundation"}, "A"),
    ("R8", "Which file format is the standard AutoCAD drawing file?",
     {"A": ".DOCX", "B": ".DWG", "C": ".XLSX", "D": ".PPTX"}, "B"),
    ("R9", "What is the purpose of the OFFSET command?",
     {"A": "Creates a parallel or concentric copy at a specified distance",
      "B": "Deletes an object", "C": "Rotates an object", "D": "Changes the drawing colour"}, "A"),
    ("R10", "Which command is used to create a polygon?",
     {"A": "POLYGON", "B": "RECTANG", "C": "PEDIT", "D": "REGION"}, "A"),
    ("R11", "A civil drawing contains many unnecessary duplicate lines and unused objects. Which tools can help clean the drawing?",
     {"A": "OVERKILL and PURGE", "B": "CIRCLE and ARC",
      "C": "MOVE and ROTATE", "D": "HATCH and FILLET"}, "A"),
]

TRAINING = [
    ("R1", "What does TNA stand for?",
     {"A": "Training Needs Analysis", "B": "Technical Network Assessment",
      "C": "Total Negotiation Activity", "D": "Training Number Allocation"}, "A"),
    ("R2", "What is FAB selling?",
     {"A": "Feature – Advantage – Benefit", "B": "Finance – Account – Booking",
      "C": "Feature – Amount – Billing", "D": "Finance – Advantage – Booking"}, "A"),
    ("R3", "Which is the BEST approach to objection handling?",
     {"A": "Listen → Clarify → Respond → Confirm", "B": "Argue → Interrupt → Discount",
      "C": "Ignore → Close → Deliver", "D": "Reject → End conversation"}, "A"),
    ("R4", "What is competency-based sales training?",
     {"A": "Training focused on measurable sales knowledge, skills and behaviours",
      "B": "Training based only on attendance", "C": "Training based only on seniority",
      "D": "Training without assessment"}, "A"),
    ("R5", "Which KPI combination provides a more complete picture of a salesperson's performance?",
     {"A": "Leads, contact rate, appointments, test drives, bookings, deliveries and conversion rates",
      "B": "Only monthly sales", "C": "Only number of calls", "D": "Only showroom footfall"}, "A"),
    ("R6", "A trainer conducts the same training programme every year despite major changes in products and customer behaviour. What is the main concern?",
     {"A": "Training content may no longer be relevant",
      "B": "The trainer is necessarily more experienced",
      "C": "Product training is unnecessary", "D": "Role-play should be eliminated"}, "A"),
    ("R7", "Which statement is an example of effective coaching feedback?",
     {"A": "You are not good at sales.",
      "B": "You interrupted the customer twice; try asking the question and allowing the customer to finish before responding.",
      "C": "You need more confidence.", "D": "Your performance is bad."}, "B"),
    ("R8", "Which training method is most effective for improving objection-handling skills?",
     {"A": "Theory + demonstration + role-play + feedback + repeated practice",
      "B": "Theory only", "C": "Product brochure only", "D": "Written exam only"}, "A"),
    ("R9", "What is the BEST profile of an experienced Automobile Sales Trainer?",
     {"A": "Strong sales experience + product knowledge + coaching ability + data analysis + communication + ethical selling",
      "B": "Product knowledge only", "C": "Public speaking only",
      "D": "Ability to achieve personal sales only"}, "A"),
]

DEPT_PAPERS: dict[str, list[tuple]] = {
    PAPER_CR_FRESHER: CR_FRESHER,
    PAPER_CR_EXPERIENCED: CR_EXPERIENCED,
    PAPER_ACCOUNTS: ACCOUNTS,
    PAPER_HR: HR,
    PAPER_SYSTEMS: SYSTEMS,
    PAPER_PROJECTS: PROJECTS,
    PAPER_INSURANCE: INSURANCE,
    PAPER_MARKETING: MARKETING,
    PAPER_FINANCE: FINANCE,
    PAPER_TRAINING: TRAINING,
}
