"""remove_branch_interview_scores

Revision ID: 0176d77f4a59
Revises: 4cfd1233aab2
Create Date: 2026-07-18 15:23:30.605305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0176d77f4a59'
down_revision: Union[str, None] = '4cfd1233aab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branch_interviews', 'dept_communication', schema='recruitment')
    op.drop_column('branch_interviews', 'dept_attitude', schema='recruitment')
    op.drop_column('branch_interviews', 'hr_knowledge', schema='recruitment')
    op.drop_column('branch_interviews', 'hr_communication', schema='recruitment')
    op.drop_column('branch_interviews', 'dept_remarks', schema='recruitment')
    op.drop_column('branch_interviews', 'dept_submitted', schema='recruitment')
    op.drop_column('branch_interviews', 'dept_knowledge', schema='recruitment')
    op.drop_column('branch_interviews', 'hr_remarks', schema='recruitment')
    op.drop_column('branch_interviews', 'hr_attitude', schema='recruitment')
    op.drop_column('branch_interviews', 'hr_submitted', schema='recruitment')
    op.drop_column('candidates', 'visit_date', schema='recruitment')
    op.drop_column('candidates', 'visit_instructions', schema='recruitment')
    op.drop_column('candidates', 'visit_maps_link', schema='recruitment')
    op.drop_column('candidates', 'visit_branch', schema='recruitment')
    op.drop_column('candidates', 'visit_time', schema='recruitment')
    op.drop_column('candidates', 'department', schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('visit_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('visit_branch', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('visit_maps_link', sa.VARCHAR(), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('visit_instructions', sa.VARCHAR(), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('visit_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('branch_interviews', sa.Column('hr_submitted', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='recruitment')
    op.add_column('branch_interviews', sa.Column('hr_attitude', sa.INTEGER(), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('branch_interviews', sa.Column('hr_remarks', sa.TEXT(), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('branch_interviews', sa.Column('dept_knowledge', sa.INTEGER(), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('branch_interviews', sa.Column('dept_submitted', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='recruitment')
    op.add_column('branch_interviews', sa.Column('dept_remarks', sa.TEXT(), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('branch_interviews', sa.Column('hr_communication', sa.INTEGER(), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('branch_interviews', sa.Column('hr_knowledge', sa.INTEGER(), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('branch_interviews', sa.Column('dept_attitude', sa.INTEGER(), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('branch_interviews', sa.Column('dept_communication', sa.INTEGER(), autoincrement=False, nullable=True), schema='recruitment')
    # ### end Alembic commands ###
