"""Phase 2 architecture and workflow updates

Revision ID: 0d08679a83f0
Revises: f01238e32a5f
Create Date: 2026-07-11 10:46:22.786015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d08679a83f0'
down_revision: Union[str, None] = 'f01238e32a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Handle ENUM modifications (Requires commit in some postgres versions, but works inside tx in pg 12+)
    op.execute("ALTER TYPE recruitment.form_status ADD VALUE IF NOT EXISTS 'EXPIRED'")
    op.execute("ALTER TYPE recruitment.screening_status RENAME VALUE 'CONTACTED' TO 'IN_PROGRESS'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('total_experience', sa.String(length=100), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('expected_salary', sa.String(length=100), nullable=True),
    sa.Column('joining_date', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('resume_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruitment.candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='recruitment'
    )
    op.create_index(op.f('ix_recruitment_candidate_profiles_candidate_id'), 'candidate_profiles', ['candidate_id'], unique=False, schema='recruitment')
    op.create_table('communications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('WHATSAPP', 'EMAIL', 'PHONE_CALL', name='communication_type', schema='recruitment'), nullable=False),
    sa.Column('direction', sa.Enum('INCOMING', 'OUTGOING', name='communication_direction', schema='recruitment'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'READ', name='communication_status', schema='recruitment'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('content_preview', sa.Text(), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruitment.candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['recruitment.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='recruitment'
    )
    op.create_index(op.f('ix_recruitment_communications_candidate_id'), 'communications', ['candidate_id'], unique=False, schema='recruitment')
    op.create_table('followups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='follow_up_priority', schema='recruitment'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='follow_up_status', schema='recruitment'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['recruitment.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruitment.candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['recruitment.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='recruitment'
    )
    op.create_index(op.f('ix_recruitment_followups_candidate_id'), 'followups', ['candidate_id'], unique=False, schema='recruitment')
    op.drop_index(op.f('ix_recruitment_candidate_application_candidate_id'), table_name='candidate_application', schema='recruitment')
    op.drop_table('candidate_application', schema='recruitment')
    op.add_column('activity_logs', sa.Column('title', sa.String(length=255), nullable=False), schema='recruitment')
    op.add_column('candidates', sa.Column('source', sa.String(length=100), server_default='Unknown', nullable=False), schema='recruitment')
    op.add_column('candidates', sa.Column('source_reference', sa.String(length=255), nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('assigned_manager_id', sa.UUID(), nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('assigned_gm_id', sa.UUID(), nullable=True), schema='recruitment')
    op.create_foreign_key(None, 'candidates', 'users', ['assigned_manager_id'], ['id'], source_schema='recruitment', referent_schema='recruitment')
    op.create_foreign_key(None, 'candidates', 'users', ['assigned_gm_id'], ['id'], source_schema='recruitment', referent_schema='recruitment')
    op.drop_column('candidates', 'source_channel', schema='recruitment')
    op.drop_column('candidates', 'source_details', schema='recruitment')
    op.drop_index(op.f('ix_documents_candidate_id'), table_name='documents', schema='recruitment')
    op.create_index(op.f('ix_recruitment_documents_candidate_id'), 'documents', ['candidate_id'], unique=False, schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruitment_documents_candidate_id'), table_name='documents', schema='recruitment')
    op.create_index(op.f('ix_documents_candidate_id'), 'documents', ['candidate_id'], unique=False, schema='recruitment')
    op.add_column('candidates', sa.Column('source_details', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('source_channel', postgresql.ENUM('WALK_IN', 'INDEED', 'REFERRAL', 'CAMPUS', 'OTHER', name='source_channel', schema='recruitment'), autoincrement=False, nullable=False), schema='recruitment')
    op.drop_constraint(None, 'candidates', schema='recruitment', type_='foreignkey')
    op.drop_constraint(None, 'candidates', schema='recruitment', type_='foreignkey')
    op.drop_column('candidates', 'assigned_gm_id', schema='recruitment')
    op.drop_column('candidates', 'assigned_manager_id', schema='recruitment')
    op.drop_column('candidates', 'source_reference', schema='recruitment')
    op.drop_column('candidates', 'source', schema='recruitment')
    op.drop_column('activity_logs', 'title', schema='recruitment')
    op.create_table('candidate_application',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('experience_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total_experience', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('current_company', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('expected_salary', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notice_period', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruitment.candidates.id'], name=op.f('candidate_application_candidate_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('candidate_application_pkey')),
    schema='recruitment'
    )
    op.create_index(op.f('ix_recruitment_candidate_application_candidate_id'), 'candidate_application', ['candidate_id'], unique=False, schema='recruitment')
    op.drop_index(op.f('ix_recruitment_followups_candidate_id'), table_name='followups', schema='recruitment')
    op.drop_table('followups', schema='recruitment')
    op.drop_index(op.f('ix_recruitment_communications_candidate_id'), table_name='communications', schema='recruitment')
    op.drop_table('communications', schema='recruitment')
    op.drop_index(op.f('ix_recruitment_candidate_profiles_candidate_id'), table_name='candidate_profiles', schema='recruitment')
    op.drop_table('candidate_profiles', schema='recruitment')
    # ### end Alembic commands ###
    
    # Drop ENUM types
    op.execute("DROP TYPE IF EXISTS recruitment.follow_up_status CASCADE")
    op.execute("DROP TYPE IF EXISTS recruitment.follow_up_priority CASCADE")
    op.execute("DROP TYPE IF EXISTS recruitment.communication_status CASCADE")
    op.execute("DROP TYPE IF EXISTS recruitment.communication_direction CASCADE")
    op.execute("DROP TYPE IF EXISTS recruitment.communication_type CASCADE")
    
    # We can't cleanly remove a value from a Postgres ENUM for form_status, so we skip downgrading EXPIRED.
    op.execute("ALTER TYPE recruitment.screening_status RENAME VALUE 'IN_PROGRESS' TO 'CONTACTED'")
