"""verify no missing columns

Revision ID: 1d2171c26366
Revises: 0748a768e009
Create Date: 2026-07-17 13:13:27.642243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d2171c26366'
down_revision: Union[str, None] = '0748a768e009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_or_link', sa.Text(), nullable=False),
    sa.Column('mode', postgresql.ENUM('PHYSICAL', 'ONLINE', name='interview_mode', schema='recruitment', create_type=False), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='recruitment'
    )
    op.create_table('message_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', postgresql.ENUM('WHATSAPP', 'EMAIL', 'PHONE_CALL', name='communication_type', schema='recruitment', create_type=False), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='recruitment'
    )
    op.drop_index(op.f('ix_recruitment_candidates_post_form_token'), table_name='candidates', schema='recruitment')
    op.drop_column('candidates', 'post_form_status', schema='recruitment')
    op.drop_column('candidates', 'post_form_submitted_at', schema='recruitment')
    op.drop_column('candidates', 'post_form_token', schema='recruitment')
    op.drop_column('candidates', 'post_form_sent_at', schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('post_form_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('post_form_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('post_form_submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('post_form_status', postgresql.ENUM('NOT_SENT', 'SENT', 'VIEWED', 'SUBMITTED', 'EXPIRED', name='form_status', schema='recruitment'), server_default=sa.text("'NOT_SENT'::recruitment.form_status"), autoincrement=False, nullable=False), schema='recruitment')
    op.create_index(op.f('ix_recruitment_candidates_post_form_token'), 'candidates', ['post_form_token'], unique=True, schema='recruitment')
    op.drop_table('message_templates', schema='recruitment')
    op.drop_table('location_templates', schema='recruitment')
    # ### end Alembic commands ###
