"""Drop application_data from candidates

Revision ID: 3f28872de64d
Revises: 0d08679a83f0
Create Date: 2026-07-11 11:14:43.586430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f28872de64d'
down_revision: Union[str, None] = '0d08679a83f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'application_data', schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('application_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='recruitment')
    # ### end Alembic commands ###
