"""Add BranchInterview

Revision ID: 4cfd1233aab2
Revises: 8d8e558968c3
Create Date: 2026-07-18 15:02:51.540719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cfd1233aab2'
down_revision: Union[str, None] = '8d8e558968c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('interview_mode', postgresql.ENUM('PHYSICAL', 'ONLINE', name='interview_mode', schema='recruitment', create_type=False), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_or_link', sa.String(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING_SCHEDULE', 'SCHEDULED', 'EVALUATED', name='interview_status', schema='recruitment', create_type=False), nullable=False),
    sa.Column('hr_attitude', sa.Integer(), nullable=True),
    sa.Column('hr_communication', sa.Integer(), nullable=True),
    sa.Column('hr_knowledge', sa.Integer(), nullable=True),
    sa.Column('hr_remarks', sa.Text(), nullable=True),
    sa.Column('hr_submitted', sa.Boolean(), nullable=False),
    sa.Column('dept_attitude', sa.Integer(), nullable=True),
    sa.Column('dept_communication', sa.Integer(), nullable=True),
    sa.Column('dept_knowledge', sa.Integer(), nullable=True),
    sa.Column('dept_remarks', sa.Text(), nullable=True),
    sa.Column('dept_submitted', sa.Boolean(), nullable=False),
    sa.Column('current_salary', sa.String(), nullable=True),
    sa.Column('expected_salary', sa.String(), nullable=True),
    sa.Column('notice_period', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruitment.candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='recruitment'
    )
    op.create_index(op.f('ix_recruitment_branch_interviews_candidate_id'), 'branch_interviews', ['candidate_id'], unique=True, schema='recruitment')
    op.drop_index(op.f('ix_recruitment_hr_interviews_candidate_id'), table_name='hr_interviews', schema='recruitment')
    op.drop_table('hr_interviews', schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_interviews',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('communication_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experience_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cultural_fit_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_salary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expected_salary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notice_period', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verdict', postgresql.ENUM('SELECTED', 'REJECTED', 'ON_HOLD', name='interview_verdict', schema='recruitment', create_type=False), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('interview_mode', postgresql.ENUM('PHYSICAL', 'ONLINE', name='interview_mode', schema='recruitment', create_type=False), autoincrement=False, nullable=True),
    sa.Column('scheduled_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('location_or_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING_SCHEDULE', 'SCHEDULED', 'EVALUATED', name='interview_status', schema='recruitment', create_type=False), server_default=sa.text("'PENDING_SCHEDULE'::recruitment.interview_status"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruitment.candidates.id'], name=op.f('hr_interviews_candidate_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('hr_interviews_pkey')),
    schema='recruitment'
    )
    op.create_index(op.f('ix_recruitment_hr_interviews_candidate_id'), 'hr_interviews', ['candidate_id'], unique=True, schema='recruitment')
    op.drop_index(op.f('ix_recruitment_branch_interviews_candidate_id'), table_name='branch_interviews', schema='recruitment')
    op.drop_table('branch_interviews', schema='recruitment')
    # ### end Alembic commands ###
