"""remove_screening_flow

Revision ID: 543b5501a7f3
Revises: 8d8e558968c3
Create Date: 2026-07-18 15:02:26.269579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.

revision: str = '543b5501a7f3'
down_revision: Union[str, None] = '8d8e558968c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('department', sa.String(length=255), nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('visit_branch', sa.String(length=255), nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('visit_date', sa.DateTime(timezone=True), nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('visit_time', sa.String(length=50), nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('visit_maps_link', sa.String(), nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('visit_instructions', sa.String(), nullable=True), schema='recruitment')
    
    # Migrate existing candidates in SCREENING to CANDIDATE_FORM
    op.execute("UPDATE recruitment.candidates SET current_stage = 'CANDIDATE_FORM' WHERE current_stage = 'SCREENING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'visit_instructions', schema='recruitment')
    op.drop_column('candidates', 'visit_maps_link', schema='recruitment')
    op.drop_column('candidates', 'visit_time', schema='recruitment')
    op.drop_column('candidates', 'visit_date', schema='recruitment')
    op.drop_column('candidates', 'visit_branch', schema='recruitment')
    op.drop_column('candidates', 'department', schema='recruitment')
    # Note: We do not downgrade the stage back to SCREENING as it's non-reversible safely
    # ### end Alembic commands ###
