"""Add missing columns for candidates and users

Revision ID: 56edb2557cf5
Revises: 71bce681c219
Create Date: 2026-07-17 11:42:01.683248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56edb2557cf5'
down_revision: Union[str, None] = '71bce681c219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruitment_candidates_post_form_token'), table_name='candidates', schema='recruitment')
    op.drop_column('candidates', 'post_form_submitted_at', schema='recruitment')
    op.drop_column('candidates', 'post_form_status', schema='recruitment')
    op.drop_column('candidates', 'post_form_sent_at', schema='recruitment')
    op.drop_column('candidates', 'post_form_token', schema='recruitment')
    op.add_column('candidates', sa.Column('is_head_office_hire', sa.Boolean(), server_default='false', nullable=False), schema='recruitment')
    op.add_column('candidates', sa.Column('interviewer_assignments', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='recruitment')
    op.add_column('users', sa.Column('department', sa.String(length=255), nullable=True), schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department', schema='recruitment')
    op.drop_column('candidates', 'interviewer_assignments', schema='recruitment')
    op.drop_column('candidates', 'is_head_office_hire', schema='recruitment')
    op.add_column('candidates', sa.Column('post_form_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('post_form_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('post_form_status', postgresql.ENUM('NOT_SENT', 'SENT', 'VIEWED', 'SUBMITTED', 'EXPIRED', name='form_status', schema='recruitment'), server_default=sa.text("'NOT_SENT'::recruitment.form_status"), autoincrement=False, nullable=False), schema='recruitment')
    op.add_column('candidates', sa.Column('post_form_submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='recruitment')
    op.create_index(op.f('ix_recruitment_candidates_post_form_token'), 'candidates', ['post_form_token'], unique=True, schema='recruitment')
    # ### end Alembic commands ###
