"""Add salary data

Revision ID: 599c6f619ba4
Revises: 9b0393b5ee82
Create Date: 2026-07-23 15:02:40.011393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '599c6f619ba4'
down_revision: Union[str, None] = '9b0393b5ee82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('salary_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'salary_data', schema='recruitment')
    # ### end Alembic commands ###
