"""add index on duplicate_of_candidate_id

Revision ID: 5d9d46dda73e
Revises: 599c6f619ba4
Create Date: 2026-07-28 14:35:08.466093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9d46dda73e'
down_revision: Union[str, None] = '599c6f619ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_recruitment_candidates_duplicate_of_candidate_id'), 'candidates', ['duplicate_of_candidate_id'], unique=False, schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruitment_candidates_duplicate_of_candidate_id'), table_name='candidates', schema='recruitment')
    # ### end Alembic commands ###
