"""replace position_applied_for with experience

Revision ID: 644d5f55c8fb
Revises: bd30025623ef
Create Date: 2026-08-08 16:30:19.840470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644d5f55c8fb'
down_revision: Union[str, None] = 'bd30025623ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('experience', sa.String(length=50), server_default='Fresher', nullable=False), schema='recruitment')
    op.drop_column('candidates', 'position_applied_for', schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('position_applied_for', sa.VARCHAR(length=255), server_default=sa.text("'Unknown'::character varying"), autoincrement=False, nullable=False), schema='recruitment')
    op.drop_column('candidates', 'experience', schema='recruitment')
    # ### end Alembic commands ###
