"""Add RBAC roles and visibility fields

Revision ID: 866937a8d89f
Revises: 58405157ddc5
Create Date: 2026-07-17 10:11:26.859677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '866937a8d89f'
down_revision: Union[str, None] = '58405157ddc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE recruitment.user_role ADD VALUE IF NOT EXISTS 'SUPER_ADMIN'")
    op.execute("ALTER TYPE recruitment.user_role ADD VALUE IF NOT EXISTS 'COMPANY_HR_HEAD'")
    op.execute("ALTER TYPE recruitment.user_role ADD VALUE IF NOT EXISTS 'BRANCH_HR'")
    op.execute("ALTER TYPE recruitment.user_role ADD VALUE IF NOT EXISTS 'DEPT_HEAD'")
    op.execute("ALTER TYPE recruitment.user_role ADD VALUE IF NOT EXISTS 'BRANCH_VP'")
    op.execute("ALTER TYPE recruitment.user_role ADD VALUE IF NOT EXISTS 'SERVICE_VP'")
    op.execute("ALTER TYPE recruitment.user_role ADD VALUE IF NOT EXISTS 'HQ_STAFF'")
    op.execute("ALTER TYPE recruitment.user_role ADD VALUE IF NOT EXISTS 'FINANCE'")
    op.add_column('candidates', sa.Column('is_head_office_hire', sa.Boolean(), server_default='false', nullable=False), schema='recruitment')
    op.add_column('candidates', sa.Column('interviewer_assignments', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='recruitment')
    op.add_column('users', sa.Column('department', sa.String(length=255), nullable=True), schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department', schema='recruitment')
    op.drop_column('candidates', 'interviewer_assignments', schema='recruitment')
    op.drop_column('candidates', 'is_head_office_hire', schema='recruitment')
    # ### end Alembic commands ###
