"""add candidate indexes

Revision ID: 9b0393b5ee82
Revises: a24100dfafac
Create Date: 2026-07-20 17:52:13.653013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b0393b5ee82'
down_revision: Union[str, None] = 'a24100dfafac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruitment_candidates_post_form_token'), table_name='candidates', schema='recruitment')
    op.create_index('ix_candidate_stage_created', 'candidates', ['current_stage', 'created_at'], unique=False, schema='recruitment')
    op.create_index(op.f('ix_recruitment_candidates_assigned_gm_id'), 'candidates', ['assigned_gm_id'], unique=False, schema='recruitment')
    op.create_index(op.f('ix_recruitment_candidates_assigned_hr_user_id'), 'candidates', ['assigned_hr_user_id'], unique=False, schema='recruitment')
    op.create_index(op.f('ix_recruitment_candidates_assigned_manager_id'), 'candidates', ['assigned_manager_id'], unique=False, schema='recruitment')
    op.create_index(op.f('ix_recruitment_candidates_branch_location'), 'candidates', ['branch_location'], unique=False, schema='recruitment')
    op.drop_column('candidates', 'post_form_status', schema='recruitment')
    op.drop_column('candidates', 'post_form_submitted_at', schema='recruitment')
    op.drop_column('candidates', 'post_form_sent_at', schema='recruitment')
    op.drop_column('candidates', 'post_form_token', schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('post_form_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('post_form_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('post_form_submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('post_form_status', postgresql.ENUM('NOT_SENT', 'SENT', 'VIEWED', 'SUBMITTED', 'EXPIRED', name='form_status', schema='recruitment'), server_default=sa.text("'NOT_SENT'::recruitment.form_status"), autoincrement=False, nullable=False), schema='recruitment')
    op.drop_index(op.f('ix_recruitment_candidates_branch_location'), table_name='candidates', schema='recruitment')
    op.drop_index(op.f('ix_recruitment_candidates_assigned_manager_id'), table_name='candidates', schema='recruitment')
    op.drop_index(op.f('ix_recruitment_candidates_assigned_hr_user_id'), table_name='candidates', schema='recruitment')
    op.drop_index(op.f('ix_recruitment_candidates_assigned_gm_id'), table_name='candidates', schema='recruitment')
    op.drop_index('ix_candidate_stage_created', table_name='candidates', schema='recruitment')
    op.create_index(op.f('ix_recruitment_candidates_post_form_token'), 'candidates', ['post_form_token'], unique=True, schema='recruitment')
    # ### end Alembic commands ###
