"""Add raw_data to CandidateProfile

Revision ID: aa3c187f50c7
Revises: a0e94e509384
Create Date: 2026-07-11 17:24:42.304534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa3c187f50c7'
down_revision: Union[str, None] = 'a0e94e509384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'raw_data', schema='recruitment')
    # ### end Alembic commands ###
