"""Add HR Interview scheduling fields

Revision ID: b3b1b70ff4cf
Revises: e08d1c7427a3
Create Date: 2026-07-14 15:42:38.566336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b1b70ff4cf'
down_revision: Union[str, None] = 'e08d1c7427a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    interview_mode = sa.Enum('PHYSICAL', 'ONLINE', name='interview_mode', schema='recruitment')
    interview_mode.create(op.get_bind())
    interview_status = sa.Enum('PENDING_SCHEDULE', 'SCHEDULED', 'EVALUATED', name='interview_status', schema='recruitment')
    interview_status.create(op.get_bind())
    
    op.add_column('hr_interviews', sa.Column('interview_mode', interview_mode, nullable=True), schema='recruitment')
    op.add_column('hr_interviews', sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True), schema='recruitment')
    op.add_column('hr_interviews', sa.Column('location_or_link', sa.String(), nullable=True), schema='recruitment')
    op.add_column('hr_interviews', sa.Column('status', interview_status, nullable=False, server_default='PENDING_SCHEDULE'), schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_interviews', 'status', schema='recruitment')
    op.drop_column('hr_interviews', 'location_or_link', schema='recruitment')
    op.drop_column('hr_interviews', 'scheduled_time', schema='recruitment')
    op.drop_column('hr_interviews', 'interview_mode', schema='recruitment')
    
    sa.Enum(name='interview_status', schema='recruitment').drop(op.get_bind())
    sa.Enum(name='interview_mode', schema='recruitment').drop(op.get_bind())
    # ### end Alembic commands ###
