"""Add index to created_at

Revision ID: bd30025623ef
Revises: 1d374251cffb
Create Date: 2026-08-07 17:08:16.228597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd30025623ef'
down_revision: Union[str, None] = '1d374251cffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_recruitment_candidates_created_at'), 'candidates', ['created_at'], unique=False, schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruitment_candidates_created_at'), table_name='candidates', schema='recruitment')
    # ### end Alembic commands ###
