"""create_hr_interview_table

Revision ID: e08d1c7427a3
Revises: ae8e0af96cd3
Create Date: 2026-07-14 10:23:06.814659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08d1c7427a3'
down_revision: Union[str, None] = 'ae8e0af96cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('communication_score', sa.Integer(), nullable=True),
    sa.Column('technical_score', sa.Integer(), nullable=True),
    sa.Column('experience_score', sa.Integer(), nullable=True),
    sa.Column('cultural_fit_score', sa.Integer(), nullable=True),
    sa.Column('current_salary', sa.String(), nullable=True),
    sa.Column('expected_salary', sa.String(), nullable=True),
    sa.Column('notice_period', sa.String(), nullable=True),
    sa.Column('verdict', sa.Enum('SELECTED', 'REJECTED', 'ON_HOLD', name='interview_verdict', schema='recruitment'), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruitment.candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='recruitment'
    )
    op.create_index(op.f('ix_recruitment_hr_interviews_candidate_id'), 'hr_interviews', ['candidate_id'], unique=True, schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruitment_hr_interviews_candidate_id'), table_name='hr_interviews', schema='recruitment')
    op.drop_table('hr_interviews', schema='recruitment')
    # ### end Alembic commands ###
