"""mvp_workflow_models

Revision ID: f01238e32a5f
Revises: 003_simplify
Create Date: 2026-07-11 10:19:56.458757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f01238e32a5f'
down_revision: Union[str, None] = '003_simplify'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### custom ENUM commands ###
    op.execute("DROP TYPE IF EXISTS recruitment.form_status CASCADE")
    op.execute("DROP TYPE IF EXISTS recruitment.screening_status CASCADE")
    op.execute("DROP TYPE IF EXISTS recruitment.activity_type CASCADE")
    
    op.execute("CREATE TYPE recruitment.form_status AS ENUM ('NOT_SENT', 'SENT', 'VIEWED', 'SUBMITTED')")
    
    op.execute("ALTER TYPE recruitment.pipeline_stage RENAME TO pipeline_stage_old")
    op.execute("""
        CREATE TYPE recruitment.pipeline_stage AS ENUM (
            'SCREENING',
            'CANDIDATE_FORM',
            'HR_INTERVIEW',
            'DEPARTMENT_INTERVIEW',
            'FINAL_APPROVAL',
            'HIRED',
            'REJECTED',
            'ON_HOLD'
        )
    """)
    # Map old values
    mapping = """
        CASE 
            WHEN current_stage::text IN ('GM_INTERVIEW', 'FINALIZING') THEN 'FINAL_APPROVAL'
            ELSE current_stage::text
        END
    """
    mapping_to = mapping.replace('current_stage', 'to_stage')
    mapping_from = mapping.replace('current_stage', 'from_stage')
    
    op.execute(f"ALTER TABLE recruitment.candidates ALTER COLUMN current_stage TYPE recruitment.pipeline_stage USING ({mapping})::recruitment.pipeline_stage")
    op.execute(f"ALTER TABLE recruitment.stage_history ALTER COLUMN to_stage TYPE recruitment.pipeline_stage USING ({mapping_to})::recruitment.pipeline_stage")
    op.execute(f"ALTER TABLE recruitment.stage_history ALTER COLUMN from_stage TYPE recruitment.pipeline_stage USING (CASE WHEN from_stage IS NULL THEN NULL ELSE ({mapping_from}) END)::recruitment.pipeline_stage")
    op.execute("DROP TYPE recruitment.pipeline_stage_old")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.Enum('CALL', 'WHATSAPP', 'EMAIL', 'STAGE_CHANGE', 'FORM', 'SYSTEM', name='activity_type', schema='recruitment'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruitment.candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['recruitment.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='recruitment'
    )
    op.create_index(op.f('ix_recruitment_activity_logs_candidate_id'), 'activity_logs', ['candidate_id'], unique=False, schema='recruitment')
    op.create_table('candidate_application',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('total_experience', sa.String(length=100), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('expected_salary', sa.String(length=100), nullable=True),
    sa.Column('notice_period', sa.String(length=100), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruitment.candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='recruitment'
    )
    op.create_index(op.f('ix_recruitment_candidate_application_candidate_id'), 'candidate_application', ['candidate_id'], unique=False, schema='recruitment')
    op.create_table('candidate_screening',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONTACTED', 'QUALIFIED', 'REJECTED', name='screening_status', schema='recruitment'), nullable=False),
    sa.Column('call_completed', sa.Boolean(), nullable=False),
    sa.Column('interest_confirmed', sa.Boolean(), nullable=False),
    sa.Column('salary_discussed', sa.Boolean(), nullable=False),
    sa.Column('notice_period_discussed', sa.Boolean(), nullable=False),
    sa.Column('basic_eligibility_checked', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruitment.candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='recruitment'
    )
    op.create_index(op.f('ix_recruitment_candidate_screening_candidate_id'), 'candidate_screening', ['candidate_id'], unique=True, schema='recruitment')

    op.add_column('candidates', sa.Column('source_details', sa.String(length=255), nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('position_applied_for', sa.String(length=255), server_default='Unknown', nullable=False), schema='recruitment')
    op.add_column('candidates', sa.Column('pre_form_token', sa.String(length=255), nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('pre_form_status', sa.Enum('NOT_SENT', 'SENT', 'VIEWED', 'SUBMITTED', name='form_status', schema='recruitment', create_type=False), nullable=False, server_default='NOT_SENT'), schema='recruitment')
    op.add_column('candidates', sa.Column('pre_form_sent_at', sa.DateTime(timezone=True), nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('pre_form_submitted_at', sa.DateTime(timezone=True), nullable=True), schema='recruitment')
    op.drop_index(op.f('ix_candidates_candidate_id'), table_name='candidates', schema='recruitment')
    op.drop_index(op.f('ix_candidates_current_stage'), table_name='candidates', schema='recruitment')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates', schema='recruitment')
    op.drop_index(op.f('ix_candidates_full_name'), table_name='candidates', schema='recruitment')
    op.drop_index(op.f('ix_candidates_phone'), table_name='candidates', schema='recruitment')
    op.create_index(op.f('ix_recruitment_candidates_candidate_id'), 'candidates', ['candidate_id'], unique=True, schema='recruitment')
    op.create_index(op.f('ix_recruitment_candidates_current_stage'), 'candidates', ['current_stage'], unique=False, schema='recruitment')
    op.create_index(op.f('ix_recruitment_candidates_email'), 'candidates', ['email'], unique=False, schema='recruitment')
    op.create_index(op.f('ix_recruitment_candidates_full_name'), 'candidates', ['full_name'], unique=False, schema='recruitment')
    op.create_index(op.f('ix_recruitment_candidates_phone'), 'candidates', ['phone'], unique=False, schema='recruitment')
    op.create_index(op.f('ix_recruitment_candidates_pre_form_token'), 'candidates', ['pre_form_token'], unique=True, schema='recruitment')
    op.drop_index(op.f('ix_stage_history_candidate_id'), table_name='stage_history', schema='recruitment')
    op.create_index(op.f('ix_recruitment_stage_history_candidate_id'), 'stage_history', ['candidate_id'], unique=False, schema='recruitment')
    op.drop_index(op.f('ix_users_email'), table_name='users', schema='recruitment')
    op.create_index(op.f('ix_recruitment_users_email'), 'users', ['email'], unique=True, schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruitment_users_email'), table_name='users', schema='recruitment')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True, schema='recruitment')
    op.drop_index(op.f('ix_recruitment_stage_history_candidate_id'), table_name='stage_history', schema='recruitment')
    op.create_index(op.f('ix_stage_history_candidate_id'), 'stage_history', ['candidate_id'], unique=False, schema='recruitment')
    op.drop_index(op.f('ix_recruitment_candidates_pre_form_token'), table_name='candidates', schema='recruitment')
    op.drop_index(op.f('ix_recruitment_candidates_phone'), table_name='candidates', schema='recruitment')
    op.drop_index(op.f('ix_recruitment_candidates_full_name'), table_name='candidates', schema='recruitment')
    op.drop_index(op.f('ix_recruitment_candidates_email'), table_name='candidates', schema='recruitment')
    op.drop_index(op.f('ix_recruitment_candidates_current_stage'), table_name='candidates', schema='recruitment')
    op.drop_index(op.f('ix_recruitment_candidates_candidate_id'), table_name='candidates', schema='recruitment')
    op.create_index(op.f('ix_candidates_phone'), 'candidates', ['phone'], unique=False, schema='recruitment')
    op.create_index(op.f('ix_candidates_full_name'), 'candidates', ['full_name'], unique=False, schema='recruitment')
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False, schema='recruitment')
    op.create_index(op.f('ix_candidates_current_stage'), 'candidates', ['current_stage'], unique=False, schema='recruitment')
    op.create_index(op.f('ix_candidates_candidate_id'), 'candidates', ['candidate_id'], unique=True, schema='recruitment')
    op.drop_column('candidates', 'pre_form_submitted_at', schema='recruitment')
    op.drop_column('candidates', 'pre_form_sent_at', schema='recruitment')
    op.drop_column('candidates', 'pre_form_status', schema='recruitment')
    op.drop_column('candidates', 'pre_form_token', schema='recruitment')
    op.drop_column('candidates', 'position_applied_for', schema='recruitment')
    op.drop_column('candidates', 'source_details', schema='recruitment')

    op.drop_index(op.f('ix_recruitment_candidate_screening_candidate_id'), table_name='candidate_screening', schema='recruitment')
    op.drop_table('candidate_screening', schema='recruitment')
    op.drop_index(op.f('ix_recruitment_candidate_application_candidate_id'), table_name='candidate_application', schema='recruitment')
    op.drop_table('candidate_application', schema='recruitment')
    op.drop_index(op.f('ix_recruitment_activity_logs_candidate_id'), table_name='activity_logs', schema='recruitment')
    op.drop_table('activity_logs', schema='recruitment')
    
    # Drop new enums
    op.execute("DROP TYPE recruitment.form_status")
    op.execute("DROP TYPE recruitment.screening_status")
    op.execute("DROP TYPE recruitment.activity_type")
    
    # Revert pipeline stage (optional, skipping for brevity, MVP downgrades rarely needed)
    # ### end Alembic commands ###
