"""Add post form tracking to Candidate

Revision ID: f30f3504b063
Revises: 58405157ddc5
Create Date: 2026-07-17 10:11:20.462874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30f3504b063'
down_revision: Union[str, None] = '58405157ddc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('post_form_token', sa.String(length=255), nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('post_form_status', sa.Enum('NOT_SENT', 'SENT', 'VIEWED', 'SUBMITTED', 'EXPIRED', name='form_status', schema='recruitment'), server_default='NOT_SENT', nullable=False), schema='recruitment')
    op.add_column('candidates', sa.Column('post_form_sent_at', sa.DateTime(timezone=True), nullable=True), schema='recruitment')
    op.add_column('candidates', sa.Column('post_form_submitted_at', sa.DateTime(timezone=True), nullable=True), schema='recruitment')
    op.create_index(op.f('ix_recruitment_candidates_post_form_token'), 'candidates', ['post_form_token'], unique=True, schema='recruitment')
    # op.create_index(op.f('ix_recruitment_evaluation_tokens_evaluation_id'), 'evaluation_tokens', ['evaluation_id'], unique=False, schema='recruitment')
    # op.drop_index(op.f('ix_recruitment_evaluations_candidate_id_type'), table_name='evaluations', schema='recruitment')
    # op.create_index(op.f('ix_recruitment_evaluations_candidate_id'), 'evaluations', ['candidate_id'], unique=False, schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruitment_evaluations_candidate_id'), table_name='evaluations', schema='recruitment')
    op.create_index(op.f('ix_recruitment_evaluations_candidate_id_type'), 'evaluations', ['candidate_id', 'type'], unique=True, schema='recruitment')
    op.drop_index(op.f('ix_recruitment_evaluation_tokens_evaluation_id'), table_name='evaluation_tokens', schema='recruitment')
    op.drop_index(op.f('ix_recruitment_candidates_post_form_token'), table_name='candidates', schema='recruitment')
    op.drop_column('candidates', 'post_form_submitted_at', schema='recruitment')
    op.drop_column('candidates', 'post_form_sent_at', schema='recruitment')
    op.drop_column('candidates', 'post_form_status', schema='recruitment')
    op.drop_column('candidates', 'post_form_token', schema='recruitment')
    # ### end Alembic commands ###
