export const GRADUATION_COURSES = [
  'B.Tech / B.E.',
  'B.Sc',
  'B.Com',
  'BBA / BBM',
  'BCA',
  'BA',
  'Diploma (Polytechnic / Technical)',
  'ITI',
  'B.Voc',
  'B.Arch',
  'B.Pharm',
  'B.Des',
  'BHM / Hotel Management',
  'LLB / Law',
  'B.Ed',
  'Nursing / Allied Health / Paramedical',
  'Other Bachelor Degree / Diploma',
] as const;

export const POST_GRADUATION_COURSES = [
  'MBA / PGDM',
  'M.Tech / M.E.',
  'MCA',
  'M.Sc',
  'M.Com',
  'MA',
  'PG Diploma',
  'MSW',
  'M.Pharm',
  'M.Arch / M.Des',
  'LLM',
  'M.Ed',
  'Executive MBA',
  'Other Master Degree / PG',
] as const;
