"""Allowlisted candidate fields for the public interviewer form."""

from __future__ import annotations

PACKET_KEYS: frozenset[str] = frozenset(
    {
        "age",
        "gender",
        "maritalStatus",
        "dateOfBirth",
        "permDistrict",
        "presDistrict",
        "languagesRead",
        "languagesWrite",
        "languagesSpeak",
        "languagesOther",
        "class10School",
        "class10Board",
        "class10Percentage",
        "class10PassingYear",
        "class10Mode",
        "class12School",
        "class12Stream",
        "class12Percentage",
        "class12PassingYear",
        "class12Mode",
        "gradCourse",
        "gradCollege",
        "gradPercentage",
        "gradPassingYear",
        "gradMode",
        "postGradCourse",
        "postGradCollege",
        "postGradPercentage",
        "postGradPassingYear",
        "postGradMode",
        "previousExperience",
        "previousJobs",
        "totalExperience",
        "expectedSalary",
        "currentSalary",
        "noticePeriod",
        "prevCompanyName",
        "prevPosition",
        "prev1Reporting",
        "prev1From",
        "prev1To",
        "prev1Salary",
        "prev1Reason",
        "prev2Name",
        "prev2Position",
        "prev2Reporting",
        "prev2From",
        "prev2To",
        "prev2Salary",
        "prev2Reason",
        "prev3Name",
        "prev3Position",
        "prev3Reporting",
        "prev3From",
        "prev3To",
        "prev3Salary",
        "prev3Reason",
        "prev4Name",
        "prev4Position",
        "prev4Reporting",
        "prev4From",
        "prev4To",
        "prev4Salary",
        "prev4Reason",
        "prevTerminated",
        "physicalDisability",
        "nervousDisorder",
        "eyeVision",
        "criminalConviction",
        "hasValidDrivingLicense",
        "confidentToDrive",
        "highestQual",
        "skills",
        "hobbies",
        "achievements",
        "expectedJoiningDate",
        "preferredRegion",
        "sourceOfOpening",
    }
)

DENIED_KEYS: frozenset[str] = frozenset(
    {
        "aadhaarNumber",
        "panNumber",
        "drivingLicenseNumber",
        "passportNumber",
        "nameAadhaar",
        "permHouseName",
        "permPostOffice",
        "permLandmark",
        "permPinCode",
        "presHouseName",
        "presPostOffice",
        "presLandmark",
        "presPinCode",
        "fatherName",
        "fatherAge",
        "fatherOccupation",
        "fatherCompany",
        "fatherPhone",
        "motherName",
        "motherAge",
        "motherOccupation",
        "motherCompany",
        "motherPhone",
        "spouseName",
        "spouseAge",
        "spouseOccupation",
        "spouseCompany",
        "spousePhone",
        "child1Relation",
        "child1Name",
        "child1Age",
        "child1Occupation",
        "child1Company",
        "child1Phone",
        "child2Relation",
        "child2Name",
        "child2Age",
        "child2Occupation",
        "child2Company",
        "child2Phone",
        "child3Relation",
        "child3Name",
        "child3Age",
        "child3Occupation",
        "child3Company",
        "child3Phone",
        "sibling1Relation",
        "sibling1Name",
        "sibling1Age",
        "sibling1Occupation",
        "sibling1Company",
        "sibling1Phone",
        "sibling2Relation",
        "sibling2Name",
        "sibling2Age",
        "sibling2Occupation",
        "sibling2Company",
        "sibling2Phone",
        "sibling3Relation",
        "sibling3Name",
        "sibling3Age",
        "sibling3Occupation",
        "sibling3Company",
        "sibling3Phone",
        "emergency1Relation",
        "emergency1Name",
        "emergency1Address",
        "emergency1Contact",
        "emergency2Relation",
        "emergency2Name",
        "emergency2Address",
        "emergency2Contact",
        "whatsapp_invite",
        "resumeFileObject",
        "resume_file",
        "resume",
        "profilePicture",
        "photoFileObject",
        "declarationName",
        "facebookUrl",
        "instagramUrl",
        "twitterUrl",
        "refContactNumber",
        "refName",
        "refRole",
        "refPanchayat",
    }
)


def _is_empty(value: object) -> bool:
    if value is None or value == "":
        return True
    if isinstance(value, (list, dict)) and len(value) == 0:
        return True
    return False


def filter_interviewer_packet(raw: dict | None) -> dict:
    if not raw:
        return {}
    packet: dict = {}
    for key, value in raw.items():
        if key in DENIED_KEYS or key not in PACKET_KEYS:
            continue
        if _is_empty(value):
            continue
        packet[key] = value
    return packet
